# Generated by Django 3.1.2 on 2020-10-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prize', models.CharField(max_length=200)),
                ('discribe', models.CharField(max_length=500)),
            ],
        ),
    ]
